### ISSUE TITLE
synthesize.py: error

### ISSUE THREAD

**Issue by NerminSalem** [mohamedkeid/Texture-Resampler#1]
hi 
thanks for sharing your work
when i attempts to run:
python3 synthesize.py ~/Texture-Synthesis/lib/images/image.jpg --out OUT
i got the following error:
![screenshot from 2017-09-08 16-58-59](https://user-images.githubusercontent.com/26221951/30217690-95c6c744-94bf-11e7-804e-743132301a0c.png)
can you help?

**Comment by NerminSalem** [comment]
and when i tried to download the weights manually, the link is not found @mohamedkeid

**Comment by mkeid** [comment]
Thanks for this @NerminSalem. With respect to your first comment, I simply had the incorrect flag name. It should be --output, not --out. Regarding the weights link, Dropbox changed their terms of service since I pushed this repo and I can no long host the weights file. I have updated the link to point to a new file.

**Comment by NerminSalem** [comment]
thanks alot for your reply @mohamedkeid but the link you updated is for the weights of vgg16 model, can you check it?
thanks

**Comment by mkeid** [comment]
Ah I'm so sorry. I just updated it. Let me know if you get it.
